### POST request to create a new patient
POST http://localhost:4001/patients
Content-Type: application/json

{
  "name": "John Doe with kafka test",
  "email": "kafk_test@test.com",
  "address": "123 main street",
  "dateOfBirth": "1995-12-11",
  "registeredDate": "2025-03-16"
}

###